### PR TITLE
38 fix some issues

### PR DESCRIPTION
**Pull request by vampirewolfB**
#38

### CODE REVIEW

**Review by sheepy-v2 — APPROVED** [review]
seems good

**Review by sheepy-v2 — CHANGES_REQUESTED** [review]
ive found that there is no email metioned anywhere even tho an email is needed to send an email in another issue

**Review by Tymuto — APPROVED** [review]
It works good did not find anything wrong

**Review by sheepy-v2 — APPROVED** [review]
seems good now

**Review by Tymuto — APPROVED** [review]
Looks good

**Pull request merged**
